src/domain/Tables/Table/Table.tsx, src/domain/Tables/Table/services/helper.ts
=> [INT-11005] Validate props passed into table.

src/domain/Avatars/Avatar/Avatar.tsx
=> [INT-10368]Add StatusDotColor property in Avatar class

src/domain/Tables/Table/Table.tsx, src/domain/Tables/Table/__snapshots__/Table.test.tsx.snap, src/domain/Tables/Table/services/helper.ts, src/domain/Tables/Table/services/style.ts, src/domain/Tables/Table/services/types.ts, src/domain/Tables/Table/subcomponents/ActionIconButtonGroup.tsx, src/domain/Tables/Table/subcomponents/TableCheckboxInput.tsx, src/domain/Tables/Table/subcomponents/TableHeader.tsx, src/domain/Tables/Table/subcomponents/TableRow.tsx, src/domain/Tables/Table/subcomponents/TableRowDataCell.tsx
=> [INT-11011] Refactor <Table> component to fix rerender issues

src/domain/Tables/Table/Table.examples.md, src/domain/Tables/Table/services/style.ts
=> [INT-11024] Make table component compatible with empty state.

src/domain/Tables/Table/services/style.ts, src/domain/Tables/Table/subcomponents/TableHeader.tsx, src/domain/Tables/Table/subcomponents/TableRow.tsx
=> [INT-11013] Fix left cell styling on table

package.json, src/domain/Tables/Table/services/style.ts, src/domain/Tables/Table/subcomponents/TableHeader.tsx, src/domain/Tables/Table/subcomponents/TableRow.tsx
=> Release 356

src/domain/Tables/Table/Table.tsx, src/domain/Tables/Table/__snapshots__/Table.test.tsx.snap, src/domain/Tables/Table/subcomponents/TableRow.tsx
=> [INT-11086] Disable hover when some row is selected

src/domain/Tables/Table/subcomponents/TableRow.tsx
=> [INT-11116] Fix progress bar with 0 progress

src/domain/Tables/Table/services/style.ts, src/domain/Tables/Table/subcomponents/TableRowDataCell.tsx
=> [INT-1109] Fix shrink column cell spacing

src/domain/Tables/Table/Table.tsx, src/domain/Tables/Table/__snapshots__/Table.test.tsx.snap
=> [INT-11138] Add tbody to table

src/domain/Tabs/ScrollingTabGroup/ScrollingTabGroup.tsx
=> [INT-11096] Add delay to rerender so there is time to render with correct scroll.

src/domain/Tables/Table/services/helper.ts, src/domain/Tables/Table/services/style.ts, src/domain/Tables/Table/subcomponents/TableHeader.tsx
=> Fix unclickable space in table title.

package.json, src/domain/Tables/Table/Table.tsx, src/domain/Tables/Table/__snapshots__/Table.test.tsx.snap, src/domain/Tables/Table/services/helper.ts, src/domain/Tables/Table/services/style.ts, src/domain/Tables/Table/subcomponents/TableHeader.tsx, src/domain/Tables/Table/subcomponents/TableRow.tsx, src/domain/Tables/Table/subcomponents/TableRowDataCell.tsx, src/domain/Tabs/ScrollingTabGroup/ScrollingTabGroup.tsx
=> Release 357

src/domain/Paginators/PaginationButtons/style.ts
=> [INT-11124] Make pagination larger on mobile.

src/domain/Callouts/EmptyState/EmptyState.examples.md, src/domain/Callouts/EmptyState/EmptyState.tsx, src/domain/Callouts/EmptyState/style.ts, src/domain/Lists/SmartList/__snapshots__/SmartList.test.tsx.snap
=> [INT-11105] Add backgroundColor prop to EmptyState

package.json, src/domain/Callouts/EmptyState/EmptyState.examples.md, src/domain/Callouts/EmptyState/EmptyState.tsx, src/domain/Callouts/EmptyState/style.ts, src/domain/Lists/SmartList/__snapshots__/SmartList.test.tsx.snap, src/domain/Paginators/PaginationButtons/style.ts
=> Release 358

src/domain/Paginators/PaginationButtons/PaginationButtons.tsx
=> [INT-11170] Reduce the page count in the PaginationButtons component in mobile

src/domain/Tables/Table/Table.examples.md, src/domain/Tables/Table/services/helper.ts, src/domain/Tables/Table/subcomponents/TableHeader.tsx, src/domain/Tables/Table/subcomponents/TableRow.tsx
=> [INT-11166] Preset large icon size on swipe actions of table

src/domain/Tabs/ScrollingTabGroup/style.ts
=> Show focus states more clearly on scrolling tab group.

src/common/types/props.ts, src/domain/Modals/Modal/Modal.examples.md, src/domain/Modals/Modal/Modal.tsx, src/domain/Modals/Modal/__snapshots__/Modal.test.tsx.snap, src/domain/Modals/Modal/style.tsx
=> [INT-9603] Support full-screen modals

package.json, src/common/types/props.ts, src/domain/Modals/Modal/Modal.examples.md, src/domain/Modals/Modal/Modal.tsx, src/domain/Modals/Modal/__snapshots__/Modal.test.tsx.snap, src/domain/Modals/Modal/style.tsx, src/domain/Paginators/PaginationButtons/PaginationButtons.tsx, src/domain/Tables/Table/Table.examples.md, src/domain/Tables/Table/services/helper.ts, src/domain/Tables/Table/subcomponents/TableHeader.tsx, src/domain/Tables/Table/subcomponents/TableRow.tsx, src/domain/Tabs/ScrollingTabGroup/style.ts
=> Release 359

src/domain/Menus/Menu/MenuItem/MenuItemContent/style.tsx
https://www.loom.com/share/e2a8055642f24eed81da4d7db647f153
=> [INT-10541] Fix MenuItem hover styling

package.json, rollup.config.js, yarn.lock
=> [INT-10220] Fix incorrect default css styles scope

src/domain/Buttons/FontAwesomeIconButton/FontAwesomeIconButton.tsx, src/domain/Buttons/FontAwesomeIconButton/__snapshots__/FontAwesomeIconButton.test.tsx.snap
=> [INT-12153] Update font awesome icon button type and button override

src/common/sass/legacy/components/_person-tag.scss, src/domain/Avatars/Avatar/Avatar.examples.md, src/domain/Avatars/Avatar/Avatar.scss
=> [INT-11615] Flip the position of status dot and status icon on Avatar component

package.json
=> Mark CSS files to have side effects

src/domain/Spacers/Margin/Margin.tsx
=> [MINOR] Export styleForMargins.

package.json
=> Fix package version.

src/domain/Lists/DraggableList/DraggableList.examples.md, src/domain/Lists/DraggableList/DraggableList.tsx
=> [INT-12242] Properly pass through keys in DraggableList

src/domain/Lists/DraggableList/style.ts
=> [INT-12241] Stop draggable list from wiggling when a card is picked up

src/domain/Lists/DraggableList/DraggableList.tsx, src/domain/Lists/DraggableList/style.ts
=> [INT-12309] Add margins props to draggable list

src/domain/Paginators/PaginationButtons/PaginationButtons.tsx, src/domain/Paginators/PaginationButtons/__snapshots__/PaginationButtons.test.tsx.snap
=> Avoid left and right buttons from submitting the form

src/domain/Inputs/HierarchicalSelectInput/HierarchicalSelectInputOption.tsx, src/domain/Inputs/HierarchicalSelectInput/TextMatch.tsx, tsconfig.json
=> [INT-11590] Implement design changes for hierachical select.

src/common/sass/app.scss
=> [INT-8469] Update Inter font download url

src/domain/Cards/Card/Card.examples.md, src/domain/Cards/Card/Card.tsx, src/domain/Cards/GroupCard/GroupCard.tsx
=> [INT-12681] Add target prop to Card and GroupCard

src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.examples.md, src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.test.tsx, src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.tsx, src/domain/Filters/FilterController/FilterController.test.tsx, src/domain/Filters/FilterController/FilterController.tsx, src/domain/Filters/FilterController/__snapshots__/FilterController.test.tsx.snap
=> [INT-12701] allow for custom inputs in AddFilterDropdownMenu

src/common/types/props.ts, src/domain/Avatars/AvatarEntity/AvatarEntity.examples.md, src/domain/Avatars/AvatarEntity/AvatarEntity.test.tsx, src/domain/Avatars/AvatarEntity/AvatarEntity.tsx, src/domain/Avatars/AvatarEntity/__snapshots__/AvatarEntity.test.tsx.snap, src/domain/Avatars/AvatarEntity/style.ts, src/domain/Timelines/VerticalTimeline/VerticalTimelineEvent/__snapshots__/VerticalTimelineEvent.test.tsx.snap
=> [INT-12452] Update avatar entity component

src/domain/Avatars/AvatarEntity/AvatarEntity.examples.md, src/domain/Avatars/AvatarEntity/AvatarEntity.tsx, src/domain/Avatars/AvatarEntity/__snapshots__/AvatarEntity.test.tsx.snap
=> [INT-12452] fix on compact avatar entity

src/domain/Forms/VerticalForm/VerticalForm.examples.md, src/domain/Forms/VerticalForm/subcomponents/Field.test.tsx, src/domain/Forms/VerticalForm/subcomponents/Field.tsx, src/domain/Forms/VerticalForm/subcomponents/__snapshots__/Field.test.tsx.snap, src/domain/Forms/VerticalForm/subcomponents/style.ts
=> [INT-12672] Add condition label to form

package.json, src/domain/Icons/Icon/FontAwesomeIconTypes/types.ts, yarn.lock
int-12648
**Patch notes:**
- Removed Icon type 'haykal'
- Added new Icon types
=> Update font awesome version to 15.13.1

src/domain/Popovers/DropdownMenu/DropdownMenu.examples.md
=> [INT-13012] Fix tooltip props on dropdown section

src/domain/Popovers/DropdownMenu/subcomponents/Section.tsx
=> [INT-13177] Fix tooltip props on dropdown section

package.json, src/domain/Internals/ExampleColorGrid/ExampleColorGrid.examples.md, src/domain/Internals/ExampleLayoutVariables/ExampleLayoutVariables.examples.md, src/domain/Internals/ExampleSpacingVariables/ExampleSpacingVariables.examples.md, src/domain/Links/UnstyledLink/UnstyledLink.tsx, styleguide.config.js, yarn.lock
=> [INT-13515] Reorganize UI Components sidebar

README.md, styleguide.config.js
=> [INT-13668] Rename to Wonka Component Factory

src/common/types/props.ts, src/domain/Links/BackLink/BackLink.examples.md, src/domain/Links/BackLink/BackLink.test.tsx, src/domain/Links/BackLink/BackLink.tsx, src/domain/Links/BackLink/index.ts, src/domain/Links/BackLink/style.ts, src/domain/Links/index.ts, src/domain/Typographies/FormattedText/__snapshots__/FormattedText.test.tsx.snap, src/domain/index.ts, styleguide.config.js
=> [INT-13715] Add back link component

src/domain/Inputs/SingleDateInput/MonthPicker.tsx, src/domain/Inputs/SingleDateInput/SingleDateInput.examples.md, src/domain/Inputs/SingleDateInput/SingleDateInput.tsx, src/domain/Inputs/SingleDateInput/__snapshots__/SingleDateInput.test.tsx.snap, src/domain/Inputs/SingleDateInput/style.scss
=> Add month and year select to single date input.

src/domain/Inputs/SingleDateInput/MonthPicker.tsx
=> [PATCH] Generate new moment on dropdown change so redux form updates correctly.

src/domain/Lists/SmartList/__snapshots__/SmartList.test.tsx.snap, src/domain/Skeletons/FormSkeleton/FormSkeleton.examples.md, src/domain/Skeletons/FormSkeleton/FormSkeleton.tsx
=> [INT-13876] Add 2 column variant and submit button toggle to FormSkeleton

src/domain/Inputs/SingleDateInput/SingleDateInput.examples.md, src/domain/Inputs/SingleDateInput/SingleDateInput.tsx
=> [INT-13880] Don't use initial visable month when value is not null.

src/domain/Boards/Board/subcomponents/Tile.tsx, src/domain/Boards/Board/subcomponents/__snapshots__/Tile.test.tsx.snap, src/domain/Buttons/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap, src/domain/Buttons/LinkButton/__snapshots__/LinkButton.test.tsx.snap, src/domain/Cards/Card/Card.tsx, src/domain/Cards/GroupCard/GroupCard.tsx, src/domain/Defaults/Defaults/Defaults.tsx, src/domain/Internals/Anchor/Anchor.test.tsx, src/domain/Internals/Anchor/Anchor.tsx, src/domain/Internals/Anchor/__snapshots__/Anchor.test.tsx.snap, src/domain/Internals/Anchor/helper.ts, src/domain/Layouts/SectionList/__snapshots__/SectionList.test.tsx.snap, src/domain/Links/ActionLink/__snapshots__/ActionLink.test.tsx.snap, src/domain/Links/UnstyledLink/__snapshots__/UnstyledLink.test.tsx.snap, src/domain/Lists/SmartList/ListClickableColumn/__snapshots__/ListClickableColumn.test.tsx.snap, src/domain/Menus/LegacyMenu/MenuItem/__snapshots__/MenuItem.test.tsx.snap, src/domain/Navigation/BreadcrumbGroup/__snapshots__/BreadcrumbGroup.test.tsx.snap, src/domain/Typographies/FormattedText/FormattedText.tsx, src/domain/Typographies/FormattedText/__snapshots__/FormattedText.test.tsx.snap, src/domain/Typographies/Text/subcomponents/Link.test.tsx, src/domain/Typographies/Text/subcomponents/Link.tsx, src/domain/Typographies/Text/subcomponents/__snapshots__/Link.test.tsx.snap
=> [INT-13323] Support openInNewTab and noreferrer rel injection in Anchor and Link

src/domain/Modals/Dialog/Dialog.tsx, src/domain/Modals/Modal/Modal.examples.md, src/domain/Modals/Modal/Modal.tsx, src/domain/Modals/Modal/__snapshots__/Modal.test.tsx.snap, src/domain/Modals/Modal/style.tsx, src/domain/Modals/Modal/subcomponents/Header.tsx, src/domain/Modals/Modal/subcomponents/__snapshots__/Content.test.tsx.snap, src/domain/Modals/Modal/subcomponents/__snapshots__/Footer.test.tsx.snap, src/domain/Modals/Modal/subcomponents/__snapshots__/Header.test.tsx.snap, src/domain/Modals/Modal/subcomponents/style.ts
=> [INT-13879] Update modal styling on mobile

src/domain/Modals/Modal/subcomponents/__snapshots__/Footer.test.tsx.snap, src/domain/Modals/Modal/subcomponents/style.ts
=> [INT-14000] Fix modal footer on mobile safari

src/domain/Links/BackLink/style.ts
=> [INT-14013] Update back link to be inline

src/domain/Modals/Dialog/Dialog.tsx
=> [INT-14188] Update dialog variant to be importable

src/domain/Formats/Record/__snapshots__/Record.test.tsx.snap, src/domain/Popovers/TooltipPopover/TooltipPopover.tsx, src/domain/Popovers/TooltipPopover/__snapshots__/TooltipPopover.test.tsx.snap
=> [INT-13167] Update Tooltip icon

src/domain/Inputs/SelectInput/SelectInput.tsx, src/domain/Inputs/TextAreaInput/TextAreaInput.tsx, src/domain/Inputs/TextInput/TextInput.tsx
=> [INT-11541] Support aria-label for certain fields

src/domain/Inputs/RadioSet/style.scss
intellihr/engineering/team-kiki/team-kiki#14351
=> [KIKI-1431] Update radio set horizontal spacing

src/common/types/props.ts, src/domain/Forms/VerticalForm/VerticalForm.examples.md, src/domain/Forms/VerticalForm/VerticalForm.tsx, src/domain/Forms/VerticalForm/subcomponents/Section/Section.tsx, src/domain/Forms/VerticalForm/subcomponents/Section/index.ts, src/domain/Forms/VerticalForm/subcomponents/Section/style.ts
intellihr/engineering/team-kiki/team-kiki#14350
=> [KIKI-14350] Add VerticalForm.Section component

package.json, src/domain/Statuses/Status/Status.examples.md, src/domain/Statuses/Status/Status.tsx, src/domain/Statuses/Status/__snapshots__/Status.test.tsx.snap, src/domain/Statuses/StatusDot/StatusDot.tsx, src/domain/Statuses/StatusDot/style.ts, yarn.lock
intellihr/engineering/guilds/front-end#14396
=> [KIKI-14396] Add isPulsing prop to Status component

src/domain/Statuses/StatusDot/style.ts
intellihr/engineering/team-kiki/team-kiki#14432
=> [KIKI-14432] Fix status dot width

src/domain/Cards/Card/Card.examples.md, src/domain/Cards/Card/Card.tsx, src/domain/Cards/Card/style.ts, src/domain/Cards/GroupCard/GroupCard.tsx, src/domain/Cards/GroupCard/style.ts
=> Hide dropdown if dropdown items are empty on cards.

src/domain/Forms/VerticalForm/VerticalForm.tsx, src/domain/Forms/VerticalForm/subcomponents/Section/Section.tsx, src/domain/Forms/VerticalForm/subcomponents/Section/style.ts
intellihr/engineering/team-kiki/team-kiki#14457
=> [KIKI-14457] Clean up form section margins

src/domain/Modals/Dialog/style.tsx, src/domain/Modals/Modal/__snapshots__/Modal.test.tsx.snap, src/domain/Modals/Modal/style.tsx
=> [INT-14397] Support long content in modal and dialog

src/domain/Statuses/Status/Status.tsx
=> [INT-14519] Fix status margins props typing

src/domain/Timelines/ModularTimeline/style/titleMarker.ts, src/domain/Timelines/ModularTimeline/style/wrappers.ts
intellihr/engineering/team-kiki/team-kiki#14558
=> [KIKI-14458] Update ModularTimeline to handle multi-line event titles

src/domain/Inputs/SelectInput/style.scss
intellihr/customer-success/bug-reports#14427
=> Fix select inputs to be the same height as text inputs (and others)

docs/Language.md
=> Add section for handling plurals

docs/Language.md
=> Update 'friendly tone' language docs to include more examples

src/domain/Lists/DraggableList/DraggableList.examples.md, src/domain/Lists/DraggableList/DraggableList.tsx
intellihr/engineering/guilds/front-end#14403
=> Add onChange prop to DraggableList

src/domain/Formats/Record/Record.examples.md, src/domain/Formats/Record/Record.test.tsx, src/domain/Formats/Record/Record.tsx, src/domain/Formats/Record/__snapshots__/Record.test.tsx.snap, src/domain/Formats/Record/style.ts
=> Add record variants

src/domain/Cards/Card/Card.tsx, src/domain/Modals/Modal/Modal.examples.md, src/domain/Modals/Modal/__snapshots__/Modal.test.tsx.snap, src/domain/Modals/Modal/style.tsx, src/domain/Modals/Modal/subcomponents/Content.test.tsx, src/domain/Modals/Modal/subcomponents/Content.tsx, src/domain/Modals/Modal/subcomponents/Header.test.tsx, src/domain/Modals/Modal/subcomponents/Header.tsx, src/domain/Modals/Modal/subcomponents/__snapshots__/Content.test.tsx.snap, src/domain/Modals/Modal/subcomponents/__snapshots__/Footer.test.tsx.snap, src/domain/Modals/Modal/subcomponents/__snapshots__/Header.test.tsx.snap, src/domain/Modals/Modal/subcomponents/style.ts
=> update modal new skinny style

src/domain/Formats/Record/Record.tsx, src/domain/Formats/Record/__snapshots__/Record.test.tsx.snap
intellihr/engineering/team-kiki/team-kiki#14680
=> Prevent Record children from being affected by component flex styles

docs/Language.md
intellihr/engineering/guilds/front-end#14395
=> Amend Language docs to correct the moment date format

src/common/types/props.ts, src/domain/Inputs/SelectInput/SelectInput.examples.md, src/domain/Inputs/SelectInput/SelectInput.tsx, src/domain/Inputs/SelectInput/__snapshots__/SelectInput.test.tsx.snap, src/domain/Inputs/SelectInput/style.scss, src/domain/Inputs/SelectInput/style.ts
=> Add margin support to select input.

src/common/types/props.ts, src/domain/Avatars/Avatar/Avatar.scss, src/domain/Avatars/AvatarEntity/AvatarEntity.examples.md, src/domain/Avatars/AvatarEntity/AvatarEntity.tsx, src/domain/Avatars/AvatarEntity/style.ts
=> Add xsmall variant for avatar entity

src/domain/Formats/Record/Record.tsx, src/domain/Formats/Record/__snapshots__/Record.test.tsx.snap, src/domain/Formats/Record/style.ts
=> Remove record label padding when it has no tooltip

src/domain/Cards/Card/style.ts, src/domain/Cards/GroupCard/style.ts
=> Remove z-index from card menu button

src/domain/Cards/Card/style.ts, src/domain/Cards/GroupCard/style.ts
=> Add z-index back to card menu button

src/domain/Callouts/EmptyState/EmptyState.tsx, src/domain/Defaults/Defaults/Defaults.tsx, src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.tsx, src/domain/Filters/FilterController/FilterController.tsx, src/domain/Filters/FilterTag/FilterTag.tsx, src/domain/Filters/FilterTag/__snapshots__/FilterTag.test.tsx.snap, src/domain/Formats/Record/Record.tsx, src/domain/Formats/Record/__snapshots__/Record.test.tsx.snap, src/domain/Formats/Statistic/Statistic.tsx, src/domain/Forms/VerticalForm/subcomponents/Field.tsx, src/domain/Forms/VerticalForm/subcomponents/__snapshots__/Field.test.tsx.snap, src/domain/Forms/VerticalForm/subcomponents/style.ts, src/domain/Inputs/HierarchicalSelectInput/HierarchicalSelectInput.tsx, src/domain/Inputs/SelectInput/SelectInput.tsx, src/domain/Inputs/SelectInput/__snapshots__/SelectInput.test.tsx.snap, src/domain/Lists/OptionList/OptionList.tsx, src/domain/Lists/SmartList/SmartList.tsx, src/domain/Lists/SmartList/__snapshots__/SmartList.test.tsx.snap, src/domain/Paginators/PaginationDetails/PaginationDetails.tsx, src/domain/Paginators/PaginationDetails/__snapshots__/PaginationDetails.test.tsx.snap, src/domain/Progress/ProgressTracker/ProgressTracker.tsx, src/domain/Tables/LegacyDataTable/DataTablePagination.tsx, src/domain/Tables/LegacyDataTable/LegacyAsyncDataTable/__snapshots__/LegacyAsyncDataTable.test.tsx.snap, src/domain/Tables/LegacyDataTable/LegacyDataTable/LegacyDataTable.tsx, src/domain/Tables/LegacyDataTable/__snapshots__/DataTablePagination.test.tsx.snap, src/domain/Tables/Table/subcomponents/TableRow.tsx
intellihr/engineering/team-kiki/team-kiki#14718
=> Add i18n support for all components with baked in english

Dockerfile-jenkins, Dockerfile-local, package.json, src/domain/Defaults/Defaults/Defaults.tsx, src/domain/Defaults/Defaults/__snapshots__/Defaults.test.tsx.snap, src/domain/Defaults/withDefaults/__snapshots__/withDefaults.test.tsx.snap, src/domain/Typographies/CurrencyText/CurrencyText.test.tsx, src/domain/Typographies/CurrencyText/CurrencyText.tsx, src/domain/Typographies/CurrencyText/__snapshots__/CurrencyText.test.tsx.snap, yarn.lock
=> Change currency text format based on locale.

src/domain/Avatars/AvatarEntity/AvatarEntity.examples.md, src/domain/Avatars/AvatarEntity/AvatarEntity.tsx, src/domain/Avatars/AvatarEntity/style.ts, src/domain/Timelines/VerticalTimeline/VerticalTimelineEvent/__snapshots__/VerticalTimelineEvent.test.tsx.snap
=> Add array support to avatar entity secondary text

src/domain/Avatars/AvatarEntity/AvatarEntity.tsx
=> Fix broken styling of avatar entity.

src/domain/Callouts/EmptyState/EmptyState.tsx, src/domain/Defaults/Defaults/Defaults.tsx, src/domain/Filters/AddFilterDropdownMenu/AddFilterDropdownMenu.tsx, src/domain/Filters/FilterController/FilterController.tsx, src/domain/Filters/FilterTag/FilterTag.tsx, src/domain/Formats/Record/Record.tsx, src/domain/Formats/Statistic/Statistic.tsx, src/domain/Forms/VerticalForm/subcomponents/Field.tsx, src/domain/Inputs/HierarchicalSelectInput/HierarchicalSelectInput.tsx, src/domain/Inputs/SelectInput/SelectInput.tsx, src/domain/Inputs/SingleDateInput/MonthPicker.tsx, src/domain/Inputs/TextAreaInput/GifSection/GifSection.tsx, src/domain/Inputs/TextAreaInput/TenorGifSelector/TenorGifSelector.tsx, src/domain/Lists/OptionList/OptionList.tsx, src/domain/Lists/SmartList/SmartList.tsx, src/domain/Paginators/PaginationDetails/PaginationDetails.tsx, src/domain/Progress/ProgressTracker/ProgressTracker.tsx, src/domain/Tables/LegacyDataTable/DataTablePagination.tsx, src/domain/Tables/LegacyDataTable/LegacyDataTable/LegacyDataTable.tsx
intellihr/engineering/team-kiki/team-kiki#14738
=> Add missing translations to components with baked in English strings and fix fallbacks

src/domain/Inputs/HierarchicalSelectInput/HierarchicalSelectInput.tsx, src/domain/Inputs/SelectInput/SelectInput.tsx, src/domain/Inputs/SelectInput/__snapshots__/SelectInput.test.tsx.snap
intellihr/engineering/team-kiki/team-kiki#14761
=> Add missing translation for select inputs

src/domain/Modals/Modal/subcomponents/__snapshots__/Header.test.tsx.snap, src/domain/Popovers/DropdownMenu/DropdownMenu.examples.md, src/domain/Popovers/DropdownMenu/DropdownMenu.test.tsx, src/domain/Popovers/DropdownMenu/__snapshots__/DropdownMenu.test.tsx.snap, src/domain/Popovers/DropdownMenu/subcomponents/Section.tsx, src/domain/Popovers/DropdownMenu/subcomponents/style.ts, src/domain/Timelines/VerticalTimeline/VerticalTimelineEvent/__snapshots__/VerticalTimelineEvent.test.tsx.snap
=> update dropdown menu support icon and secondary icon

src/domain/Buttons/FontAwesomeIconButton/FontAwesomeIconButton.examples.md, src/domain/Buttons/FontAwesomeIconButton/FontAwesomeIconButton.test.tsx, src/domain/Buttons/FontAwesomeIconButton/FontAwesomeIconButton.tsx, src/domain/Buttons/FontAwesomeIconButton/__snapshots__/FontAwesomeIconButton.test.tsx.snap, src/domain/Buttons/FontAwesomeIconButton/colors.ts, src/domain/Buttons/FontAwesomeIconButton/style.ts, src/domain/Layouts/SectionList/__snapshots__/SectionList.test.tsx.snap
=> Update font awesome icon button to support icon size and status dot
